#THIS WILL BE THE ELEMENT RESPONSIBLE FOR ACTUATING THE BRAKE CONTROL IN CASE IT NEEDS TO BRAKE ANY OF THE WHEELS DUE TO A LOSS OF
#CONTROL OF THE VEHICLE. THE WAY THIS WORKS IS BY RECEIVING DIRECT INSTRUCTIONS FROM THE CONTROL UNIT, WHICH IN CASE OF DETECTING
#SLIDING OR ANY LOSS OF CONTROL OVER THE VEHICLE, IT WILL INDIVIDUALLY BRAKE EACH WHEEL AS NEEDED TO HELP CORRECT THE PATH OF THE VEHICLE