#THIS SENSOR MEASURES DATA ON THE ROTATIONAL AXIS OF THE VEHICLE. MEASURING WHETHER OR NOT IT IS TURNING FROM ITS BACK OR FRONT.
#THIS WOULD MEAN THAT EITHER FRONT OR REAR WHEELS HAVE STARTED SLIPPING AND ARE EITHER NOT IN CONTACT WITH THE GROUND ANYMORE OR
#ON SLIPPERY PAVEMENT, RESULTING THEREFORE IN A LOSS OF CONTROL OF THE VEHICLE